### PR TITLE
Remove get_holes()

### PR DESCRIPTION
**Pull request by tigertv**
What do you think? Or use a sctruct for this?

### CODE REVIEW

**Comment by jubalh** [comment]
It's a good idea.
Maybe we can even go further and remove `get_holes()` from sudoku.{c,h} and just assign  the value in main.c

**Comment by jubalh** [comment]
For the git commit message please read: https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53 :)

**Comment by tigertv** [comment]
:) Short summary is 69 .)  OK. How to change this? I mean text of the commit message.

**Comment by jubalh** [comment]
If it's your last commit you can use: `git commit --amend` for earlier commits you will have to use rebase again :)

**Comment by tigertv** [comment]
I used --amend before. 

You've written:
For the git commit message please read: https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53 :)

Is my commit message is not OK?

**Comment by jubalh** [comment]
Thanks for the renaming of the commit summary :) I like it better like this.
Additionally I edited the commit message to be a little more verbose.

Merged in https://github.com/jubalh/nudoku/commit/7989d1f663ba2163d58faad1ac8a627db8a6c998

**Comment by tigertv** [comment]
Yes, the commit message is more understandable now.

**Pull request closed without merging**
