### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by tigertv**
Refactored sudoku.c and main.c

### CODE REVIEW

**Comment by jubalh** [comment]
@tigertv I tried to pull from your repo but it seems its not available on GitHub anymore?

**Comment by tigertv** [comment]
Hmmm. I removed the fork. I didn´t know it can cause a problem... 
But the files are here, how can it be possible? Do I need to fork again?

**Comment by jubalh** [comment]
Not sure. Usually I dont use github to merge, but pull on the commandline and then merge locally.

**Comment by tigertv** [comment]
Remove the PR and do a new PR?

**Comment by jubalh** [comment]
Maybe it's already enough to push your local repo back to GitHub.
Meaning: Forking on GH and pushing the changes you made to it again. If it's at the same location/branch maybe GitHub figures it out.

Just try something :)

**Pull request closed without merging**
