### PR TITLE
Add i18n support, spanish and german translations

### PR DESCRIPTION
**Pull request by Ramshell**
This pr is the clean version of [this one](https://github.com/jubalh/nudoku/pull/11).

### CODE REVIEW

**Comment by Ramshell** [comment]
I've closed the other pr and open this one with my master branch and the changes you asked ;). If there is anything else just tell me.

**Review by jubalh — CHANGES_REQUESTED** [review]

**Comment by Ramshell** [comment]
Done! I thought it is better to update the README in the Add i18n support commit, so I've done that too. Again, If there is anything else just tell me.

**Comment by jubalh** [comment]
I would like to add your names to the `AUTHORS` file.
Usually I write: firstname 'nickname' surname: email@domain.es
Are you ok with this? Would you mind providing the information?

**Comment by Ramshell** [comment]
Ohh. Okay here it goes:
* Nicolás 'Ramshell' Leutwyler: ramshellcinox@gmail.com
* Emanuel Dubor: emanueldubor@gmail.com (no nickname :-1: )

**Comment by jubalh** [comment]
Perfect. Thanks for your contribution!

Done in https://github.com/jubalh/nudoku/commit/afbba00d1abd3752ba8c7916b8997c9a80fa1618

**Pull request merged**
