### PR TITLE
Allow users to disable NLS

### PR DESCRIPTION
**Pull request by equal-l2**

### CODE REVIEW

**Comment by jubalh** [comment]
If we don't use setlocale(), bindtextdomain(), and textdomain(). Will the _() functions work anyways?

Also if we have it like this let's have ENABLE_NLS on by default.

**Comment by equal-l2** [comment]
`ENABLE_NLS` is set by `configure` script.
`configure` sets `ENABLE_NLS` to `0` if gettext cannot be found or if it is passed `--disable-nls` explicitly by users.

**Comment by jubalh** [comment]
I see. Only looked it up now. Thanks for the patch :)

**Comment by jubalh** [comment]
@equal-l2 I would add you to the AUTHORS file.
Usually I use the format: `firstname 'nickname' surname: email`

Do you want to provide said information so I can add it, or be added by your nickname/email only?

**Comment by jubalh** [comment]
Done in https://github.com/jubalh/nudoku/commit/625eea0b9b938a92d3d55386033e45071dad495b

**Pull request merged**
