### PR TITLE
Russian translations for nudoku package.

### PR DESCRIPTION
**Pull request by tigertv**
Hi! I added Russian translations.

### CODE REVIEW

**Comment by jubalh** [comment]
Nice, thank you!
Can you in the same commit also add `ru` to https://github.com/jubalh/nudoku/blob/master/po/LINGUAS ?

**Comment by tigertv** [comment]
OK.

**Comment by tigertv** [comment]
Done.

**Comment by tigertv** [comment]
When I try to use HEAD~3 it gives: 

pick afbba00 Add Nicolas and Emanuel to AUTHORS
  2 pick 93ca077 Russian translations for nudoku package.
  3 pick 4ce299b I added Russian translations.

Is it right? I didn't rebase before.

**Comment by jubalh** [comment]
That is right. Then you change it to:
```
pick afbba00 Add Nicolas and Emanuel to AUTHORS
pick 93ca077 Russian translations for nudoku package.
s 4ce299b I added Russian translations.
```

And save and close. Then it will open the editor again. There you remove the text and just write "Add Russian translation"

**Comment by jubalh** [comment]
After this you will have to force push (`git push -f`) to your branch and this PR will be updated.

**Comment by tigertv** [comment]
Done. Thanks for the instructions!

**Comment by jubalh** [comment]
Well done! Thanks for your contribution.
I will add you to the `AUTHORS` file like this: `firstname `nickname` surname: email@domain.org` are you okay with that?

**Comment by tigertv** [comment]
OK.

**Pull request merged**
